[project]
name = "ingress"
version = "0.1.0"
description = "Mastodon federated timeline list ingress service"
requires-python = ">=3.12"
dependencies = [
    "psycopg2-binary>=2.9.10",
    "redis>=6.4.0",
    "requests>=2.32.4",
]
